library digikam.constants;

import 'package:dropdown_textfield/dropdown_textfield.dart';

const ratingValues = [
  DropDownValueModel(value: "0", name: "--"),
  DropDownValueModel(value: "1", name: "*"),
  DropDownValueModel(value: "2", name: "**"),
  DropDownValueModel(value: "3", name: "***"),
  DropDownValueModel(value: "4", name: "****"),
  DropDownValueModel(value: "5", name: "*****"),
];
const isoValues = [
  DropDownValueModel(value: "0", name: "0"),
  DropDownValueModel(value: "50", name: "50"),
  DropDownValueModel(value: "64", name: "64"),
  DropDownValueModel(value: "100", name: "100"),
  DropDownValueModel(value: "200", name: "200"),
  DropDownValueModel(value: "400", name: "400"),
  DropDownValueModel(value: "800", name: "800"),
  DropDownValueModel(value: "1600", name: "1600"),
  DropDownValueModel(value: "3200", name: "3200"),
  DropDownValueModel(value: "6400", name: "6400"),
  DropDownValueModel(value: "12800", name: "12800"),
  DropDownValueModel(value: "25600", name: "25600"),
  DropDownValueModel(value: "1000000", name: "∞"),
];
const apertureValues = [
  DropDownValueModel(value: "0", name: "0"),
  DropDownValueModel(value: "1", name: "1"),
  DropDownValueModel(value: "1.4", name: "1.4"),
  DropDownValueModel(value: "1.7", name: "1.7"),
  DropDownValueModel(value: "2", name: "2"),
  DropDownValueModel(value: "2.8", name: "2.8"),
  DropDownValueModel(value: "4.0", name: "4"),
  DropDownValueModel(value: "5.6", name: "5.6"),
  DropDownValueModel(value: "8.0", name: "8"),
  DropDownValueModel(value: "11.0", name: "11"),
  DropDownValueModel(value: "16.0", name: "16"),
  DropDownValueModel(value: "22.0", name: "22"),
  DropDownValueModel(value: "32.0", name: "32"),
  DropDownValueModel(value: "45.0", name: "45"),
  DropDownValueModel(value: "1000000", name: "∞"),
];
const focalLengthValues = [
  DropDownValueModel(value: "0", name: "0"),
  DropDownValueModel(value: "10", name: "10"),
  DropDownValueModel(value: "15", name: "15"),
  DropDownValueModel(value: "20", name: "20"),
  DropDownValueModel(value: "25", name: "25"),
  DropDownValueModel(value: "30", name: "30"),
  DropDownValueModel(value: "35", name: "35"),
  DropDownValueModel(value: "50", name: "50"),
  DropDownValueModel(value: "60", name: "60"),
  DropDownValueModel(value: "70", name: "70"),
  DropDownValueModel(value: "80", name: "88"),
  DropDownValueModel(value: "90", name: "90"),
  DropDownValueModel(value: "100", name: "100"),
  DropDownValueModel(value: "150", name: "150"),
  DropDownValueModel(value: "200", name: "200"),
  DropDownValueModel(value: "300", name: "300"),
  DropDownValueModel(value: "400", name: "400"),
  DropDownValueModel(value: "500", name: "500"),
  DropDownValueModel(value: "700", name: "700"),
  DropDownValueModel(value: "1000", name: "1000"),
  DropDownValueModel(value: "1000000", name: "∞"),
];
const exposureValues = [
  DropDownValueModel(value: "0", name: "0"),
  DropDownValueModel(value: "8000", name: "1/8000"),
  DropDownValueModel(value: "4000", name: "1/4000"),
  DropDownValueModel(value: "2000", name: "1/2000"),
  DropDownValueModel(value: "1000", name: "1/1000"),
  DropDownValueModel(value: "500", name: "1/500"),
  DropDownValueModel(value: "250", name: "1/250"),
  DropDownValueModel(value: "125", name: "1/125"),
  DropDownValueModel(value: "60", name: "1/60"),
  DropDownValueModel(value: "30", name: "1/30"),
  DropDownValueModel(value: "15", name: "1/15"),
  DropDownValueModel(value: "8", name: "1/8"),
  DropDownValueModel(value: "4", name: "1/4"),
  DropDownValueModel(value: "2", name: "1/2"),
  DropDownValueModel(value: "1", name: "1"),
  DropDownValueModel(value: "0.5", name: "2"),
  DropDownValueModel(value: "0.25", name: "4"),
  DropDownValueModel(value: "0.125", name: "8"),
  DropDownValueModel(value: "0.0625", name: "16"),
  DropDownValueModel(value: "0.03125", name: "32"),
  DropDownValueModel(value: "0.00001", name: "∞"),
];
const orientationValues = [
  DropDownValueModel(value: "portrait", name: "Hochformat"),
  DropDownValueModel(value: "landscape", name: "Querformat"),
];